# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Setup Kani Dependencies
inputs:
  os:
    description: In which Operating System is this running
    required: true
runs:
  using: composite
  steps:
      - name: Install dependencies
        run: ./scripts/setup/${{ inputs.os }}/install_deps.sh
        shell: bash

      - name: Install CBMC
        run: ./scripts/setup/${{ inputs.os }}/install_cbmc.sh
        shell: bash

      - name: Install cbmc-viewer
        run: ./scripts/setup/${{ inputs.os }}/install_viewer.sh
        shell: bash

      - name: Install Rust toolchain
        run: ./scripts/setup/install_rustup.sh
        shell: bash

      - name: Update submodules
        run: |
          git submodule update --init --depth 1
        shell: bash
