# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Setup Kani Dependencies
inputs:
  os:
    description: In which Operating System is this running
    required: true
  kani_dir:
    description: Path to Kani's root directory
    required: false
    default: '.'
runs:
  using: composite
  steps:
      - name: Remove unnecessary software to free up disk space
        if: contains(fromJSON('["ubuntu-18.04","ubuntu-20.04","ubuntu-22.04"]'), inputs.os)
        shell: bash
        run: |
          # inspired by https://github.com/easimon/maximize-build-space/blob/master/action.yml
          df -h
          echo $PATH
          ls /
          ls /opt
          ls -la /usr/local/.ghcup/bin
          ls -la /home/runner/.dotnet/tools
          which ghc
          sudo rm -r /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Install dependencies
        run: cd ${{ inputs.kani_dir }} && ./scripts/setup/${{ inputs.os }}/install_deps.sh
        shell: bash

      - name: Install Rust toolchain
        run: cd ${{ inputs.kani_dir }} && ./scripts/setup/install_rustup.sh
        shell: bash

      - name: Update submodules
        run: |
          cd ${{ inputs.kani_dir }}
          git config --global --add safe.directory $(pwd)
          git submodule update --init --depth 1
        shell: bash
