# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Setup Kani Dependencies
inputs:
  os:
    description: In which Operating System is this running
    required: true
runs:
  using: composite
  steps:
      - name: Install dependencies
        run: ./scripts/setup/${{ inputs.os }}/install_deps.sh

      - name: Install CBMC
        run: ./scripts/setup/${{ inputs.os }}/install_cbmc.sh

      # This is unfortunate, but cbmc-viewer currently requires Python >= 3.8
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install cbmc-viewer
        run: ./scripts/setup/install_viewer.sh 2.11

      - name: Install Rust toolchain
        run: ./scripts/setup/install_rustup.sh

      - name: Update submodules
        run: |
          git submodule update --init --depth 1
