# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
[book]
title = "The Kani Rust Verifier"
description = "Documentation for the Kani Rust Verifier"
authors = ["Kani Developers"]
src = "src"
language = "en"
multilingual = false

[output.html]
site-url = "/kani/"
git-repository-url = "https://github.com/model-checking/rmc"
edit-url-template = "https://github.com/model-checking/rmc/edit/main/kani-docs/{path}"
