[package]
name = "error_index_generator"
version = "0.0.0"
edition = "2021"

[dependencies]
rustdoc = { path = "../../librustdoc" }

[build-dependencies]
walkdir = "2"

[[bin]]
name = "error_index_generator"
path = "main.rs"
