[package]
name = "rustc_type_ir"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
bitflags = "1.2.1"
rustc_index = { path = "../rustc_index" }
rustc_serialize = { path = "../rustc_serialize" }
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_macros = { path = "../rustc_macros" }
