[package]
name = "rustbook"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = "2.25.0"
env_logger = "0.7.1"

[dependencies.mdbook]
version = "0.4.14"
default-features = false
features = ["search"]
