[package]
name = "rustc_target"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.2.1"
tracing = "0.1"
rustc_data_structures = { path = "../rustc_data_structures" }
rustc_macros = { path = "../rustc_macros" }
rustc_serialize = { path = "../rustc_serialize" }
rustc_span = { path = "../rustc_span" }
rustc_index = { path = "../rustc_index" }
