[package]
name = "core"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/rust.git"
description = "The Rust Core Library"
autotests = false
autobenches = false
edition = "2021"

[lib]
test = false
bench = false

[[test]]
name = "coretests"
path = "tests/lib.rs"

[[bench]]
name = "corebenches"
path = "benches/lib.rs"
test = true

[dev-dependencies]
rand = "0.7"

[features]
# Make panics and failed asserts immediately abort without formatting any message
panic_immediate_abort = []
# Make `RefCell` store additional debugging information, which is printed out when
# a borrow error occurs
debug_refcell = []
