# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Note: this file is intended only for testing the kani release bundle
# This docker assumes the following locations:
# - ./kani_src/: Kani source code
# - ./kani-*tar.bz/: The Kani release bundle. E.g. `kani-0.39.0-x86_64-unknown-linux-gnu.tar.gz`
# - ./linux-kani-verifier.crate: The kani-verifier package

FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true
RUN apt-get update && \
    apt-get install -y python3 python3-pip curl ctags && \
    curl -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /tmp/kani
COPY ./kani_src/tests ./tests

# This will extract things into kani-verifier-${VERSION} folder
COPY ./linux-kani-verifier.crate ./kani-verifier.crate
RUN tar zxvf ./kani-verifier.crate
RUN cargo install --path ./kani-verifier-*

COPY ./kani-*.tar.gz ./
RUN cargo-kani setup --use-local-bundle ./kani-*.tar.gz
