# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "cbmc-unknown-lang-mode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# zerocopy 0.8.60 (pulled in by rand through ppv-lite86) doesn't compile under `--cfg kani`
# without its `derive` feature. Remove once a fixed release is out:
# https://github.com/model-checking/kani/issues/4988
zerocopy = "=0.8.59"
getrandom = "0.2"
rand = "0.8.0"

[workspace]
