# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Modifications Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# See GitHub history for details.
[book]
title = "The Rust Unstable Book"
author = "The Rust Community"

[output.html]
git-repository-url = "https://github.com/rust-lang/rust/tree/master/src/doc/unstable-book"
