[package]
name = "rustc_ast_pretty"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
tracing = "0.1"
rustc_span = { path = "../rustc_span" }
rustc_ast = { path = "../rustc_ast" }
