-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]
import Base
open Primitives
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace test

/- [test::tuple_add]:
   Source: 'test.rs', lines 7:1-7:36 -/
def tuple_add (t : (I32 × I32)) : Result I32 :=
  let (i, i1) := t
  i + i1

/- [test::main]:
   Source: 'test.rs', lines 12:1-12:10 -/
def main : Result Unit :=
  do
  let _ ← tuple_add (1#i32, 2#i32)
  Result.ok ()

end test
