[package]
name = "rustc_llvm"
version = "0.0.0"
edition = "2021"

[features]
static-libstdcpp = []
emscripten = []

[dependencies]
libc = "0.2.73"

[build-dependencies]
build_helper = { path = "../../src/build_helper" }
cc = "1.0.69"
