[package]
name = "rustc_index"
version = "0.0.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
arrayvec = { version = "0.7", default-features = false }
rustc_serialize = { path = "../rustc_serialize" }
rustc_macros = { path = "../rustc_macros" }
smallvec = "1"
