-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]
import Base
open Primitives
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace test

/- [test::MyEnum]
   Source: 'test.rs', lines 8:1-8:12 -/
inductive MyEnum :=
| A : I32 → MyEnum
| B : MyEnum

/- [test::enum_match]:
   Source: 'test.rs', lines 14:1-14:32 -/
def enum_match (e : MyEnum) : Result I32 :=
  match e with
  | MyEnum.A i => Result.ok i
  | MyEnum.B => Result.ok 0#i32

/- [test::main]:
   Source: 'test.rs', lines 24:1-24:10 -/
def main : Result Unit :=
  do
  let _ ← enum_match (MyEnum.A 1#i32)
  Result.ok ()

end test
