-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [test]
import Base
open Primitives
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace test

/- [test::tuple_fn]:
   Source: 'test.rs', lines 38:1-38:33 -/
def tuple_fn (t : (I32 × I32)) : Result I32 :=
  let (i, i1) := t
  i + i1

/- [test::main]:
   Source: 'test.rs', lines 43:1-43:10 -/
def main : Result Unit :=
  do
  let _ ← tuple_fn (1#i32, 2#i32)
  Result.ok ()

end test
