// Copyright Kani Contributors
// SPDX-License-Identifier: Apache-2.0 OR MIT
// kani-flags: -Zfunction-contracts

//! Soundness regression for the contract-closure capture-load check elision.
//!
//! The elision must fire only for closures generated by the contract macros,
//! never for a user-written closure that merely sits inside a contracted
//! function. A user `FnOnce` closure has the same by-value environment and
//! by-reference captures as a contract closure, but — unlike a contract
//! closure, which is invoked in place — it can escape the frame (here via a
//! boxed `dyn FnOnce` whose lifetime is erased with `transmute`) and be called
//! after the captured local is dead. Its capture load is then a genuine
//! dangling dereference that must stay checked; eliding it would be a false
//! negative. Verification must fail on the dead-object dereference.

static mut ESCAPED: Option<Box<dyn FnOnce() -> i32>> = None;

#[kani::ensures(|_| true)]
fn stash() {
    let x: i32 = 42;
    let owned = Box::new(0u8);
    // Non-`move` closure: reads `x` (a by-reference capture) and consumes
    // `owned` (a by-value capture), which forces the closure to be `FnOnce`
    // and gives it the by-value environment the elision keys on.
    let escaping = || {
        let _consume = owned;
        x
    };
    // Erase the closure's lifetime so it can outlive `x`'s frame.
    unsafe {
        ESCAPED = Some(std::mem::transmute::<
            Box<dyn FnOnce() -> i32 + '_>,
            Box<dyn FnOnce() -> i32 + 'static>,
        >(Box::new(escaping)));
    }
}

#[kani::proof]
fn escaping_capture_load_is_still_checked() {
    stash();
    // `x`'s frame is dead; invoking the escaped closure dereferences a
    // dangling `&x`. This UB must be caught.
    let escaped = unsafe { ESCAPED.take().unwrap() };
    let _ = escaped();
}
