[package]
name = "rustc-workspace-hack"
version = "1.0.0"
license = 'MIT OR Apache-2.0'
description = """
Hack for the compiler's own build system
"""
edition = "2021"

[lib]
path = "lib.rs"

# For documentation about what this is and why in the world these dependencies
# are appearing, see `README.md`.

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
  "accctrl",
  "aclapi",
  "basetsd",
  "cfg",
  "consoleapi",
  "errhandlingapi",
  "evntrace",
  "fibersapi",
  "in6addr",
  "inaddr",
  "ioapiset",
  "jobapi",
  "jobapi2",
  "knownfolders",
  "libloaderapi",
  "lmcons",
  "memoryapi",
  "minschannel",
  "minwinbase",
  "mstcpip",
  "mswsock",
  "namedpipeapi",
  "ntdef",
  "ntsecapi",
  "ntstatus",
  "objbase",
  "processenv",
  "processthreadsapi",
  "profileapi",
  "psapi",
  "schannel",
  "securitybaseapi",
  "shellapi",
  "shlobj",
  "sspi",
  "synchapi",
  "sysinfoapi",
  "threadpoollegacyapiset",
  "timezoneapi",
  "userenv",
  "winbase",
  "wincon",
  "wincrypt",
  "windef",
  "winioctl",
  "winsock2",
  "ws2def",
  "ws2ipdef",
  "ws2tcpip",
]

[dependencies]
bstr = { version = "0.2.13", features = ["default"] }
byteorder = { version = "1", features = ['default', 'std'] }
curl-sys = { version = "0.4.13", features = ["http2", "libnghttp2-sys"], optional = true }
crossbeam-utils = { version = "0.8.0", features = ["nightly"] }
libc = { version = "0.2.79", features = ["align"] }
# Ensure default features of libz-sys, which are disabled in some scenarios.
libz-sys = { version = "1.1.2" }
proc-macro2 = { version = "1", features = ["default"] }
quote = { version = "1", features = ["default"] }
rand_core_0_5 = { package = "rand_core", version = "0.5.1", features = ["getrandom", "alloc", "std"] }
serde = { version = "1.0.82", features = ['derive'] }
serde_json = { version = "1.0.31", features = ["raw_value", "unbounded_depth"] }
smallvec = { version = "1.6.1", features = ['union', 'may_dangle'] }
syn = { version = "1", features = ['fold', 'full', 'extra-traits', 'visit', 'visit-mut'] }
url = { version = "2.0", features = ['serde'] }

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10.35", optional = true }

[features]
all-static = ['openssl/vendored', 'curl-sys/static-curl', 'curl-sys/force-system-lib-on-osx']
