# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "make-kani-release"
version = "0.1.0"
edition = "2021"
description = "Contructs a Kani release bundle"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
which = "4"
