#!/usr/bin/env bash
# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
REPO_DIR="$(dirname $SCRIPT_DIR)"

shopt -s nullglob
KANI_CANDIDATES=("$REPO_DIR"/target/*/kani-driver)

if [[ -z ${KANI_CANDIDATES:-""} ]] || [[ ${#KANI_CANDIDATES[@]} -ne 1 ]]
then
    echo "ERROR: Could not find kani-driver binary."
    echo "Looked for: '$REPO_DIR/target/*/kani-driver'"
    echo "Was Kani successfully built first?"
    exit 1
fi
KANI_PATH=${KANI_CANDIDATES[0]}

# if the crate uses proptest, get ready to run that. Make sure local
# proptest import and kani's proptest does not clash.
if tomlq '.target."cfg(not(kani))".dependencies.proptest' Cargo.toml  > /dev/null; then
    if [ -z "${CARGO_KANI_IS_CHILD+x}" ]; then
        $SCRIPT_DIR/refresh-kani-proptest.sh
        export IS_KANI_PROPTEST=1
    fi
else
    echo "Clashing import of proptest. Stopping cargo kani."
    echo "Please put your proptest import under [target.'cfg(not(kani))'.dependencies]"
    exit 1
fi

exec -a cargo-kani "${KANI_PATH}" "$@"
EXIT_CODE="$?"
