#!/usr/bin/env bash
# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
REPO_DIR="$(dirname $SCRIPT_DIR)"

shopt -s nullglob
KANI_CANDIDATES=("$REPO_DIR"/target/*/kani-driver)

if [[ -z ${KANI_CANDIDATES:-""} ]] || [[ ${#KANI_CANDIDATES[@]} -ne 1 ]]
then
    echo "ERROR: Could not find kani-driver binary."
    echo "Looked for: '$REPO_DIR/target/*/kani-driver'"
    echo "Was Kani successfully built first?"
    exit 1
fi
KANI_PATH=${KANI_CANDIDATES[0]}

if [ -z "${CARGO_KANI_IS_CHILD+x}" ]; then
    # avoid infinite recursion as below script also calls `cargo kani`
    $SCRIPT_DIR/refresh-kani-proptest.sh
fi

CARGO_TOML_SAVE_FILE='.save-cargo.toml'
if [[ "${PROPTEST+x}" == "1" ]]; then
    cp Cargo.toml $CARGO_TOML_SAVE_FILE
    cat Cargo.toml |  sed 's/^\s*proptest.*$//g' | tee Cargo.toml 1>/dev/null

fi

exec -a cargo-kani "${KANI_PATH}" "$@"
EXIT_CODE="$?"

# todo! Somehow, this is not running. Exits fro cargo kani error.
cat $CARGO_TOML_SAVE_FILE > Cargo.toml
exit $EXIT_CODE
