#!/usr/bin/env bash
# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
REPO_DIR="$(dirname $SCRIPT_DIR)"

shopt -s nullglob
KANI_CANDIDATES=("$REPO_DIR"/target/*/kani-driver)

if [[ -z ${KANI_CANDIDATES:-""} ]] || [[ ${#KANI_CANDIDATES[@]} -ne 1 ]]
then
    echo "ERROR: Could not find kani-driver binary."
    echo "Looked for: '$REPO_DIR/target/*/kani-driver'"
    echo "Was Kani successfully built first?"
    exit 1
fi
KANI_PATH=${KANI_CANDIDATES[0]}

$SCRIPT_DIR/refresh-kani-proptest.sh

exec -a kani "${KANI_PATH}" "$@"
