# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
ignore = "E302"  # Ignore 2 spaces before functions until we fix fn docstrings
