#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT

import argparse
import os
import sys
import rmc
import rmc_flags
import pathlib

MY_PATH = pathlib.Path(__file__).parent.parent.absolute()
RMC_C_LIB = MY_PATH / "library" / "rmc" / "rmc_lib.c"
RMC_C_STUB = MY_PATH / "library" / "rmc" / "rmc_stub.c"
EXIT_CODE_SUCCESS = 0
CBMC_VERIFICATION_FAILURE_EXIT_CODE = 10

def main():
    args = parse_args()

    rmc.ensure_dependencies_in_path()

    base, ext = os.path.splitext(args.input)
    rmc.ensure(ext == ".rs", "Expecting .rs input file.")

    if args.gen_c_runnable:
        json_runnable_filename = base + "_runnable.json"
        goto_runnable_filename = base + "_runnable.goto"
        c_runnable_filename = base + "_runnable.c"
        if EXIT_CODE_SUCCESS != rmc.compile_single_rust_file(args.input, json_runnable_filename, args.verbose, args.debug, args.keep_temps, args.mangler, args.dry_run, ["gen-c"]):
            return 1

        if EXIT_CODE_SUCCESS != rmc.symbol_table_to_gotoc(json_runnable_filename, goto_runnable_filename, args.verbose, args.keep_temps, args.dry_run):
            return 1

        if EXIT_CODE_SUCCESS != rmc.link_c_lib(goto_runnable_filename, goto_runnable_filename, args.c_lib, args.verbose, args.quiet, args.function, args.dry_run):
            return 1

        if EXIT_CODE_SUCCESS != rmc.goto_to_c(goto_runnable_filename, c_runnable_filename, args.verbose, args.dry_run):
            return 1
        
        rmc.gen_c_postprocess(c_runnable_filename, args.dry_run)

    json_filename = base + ".json"
    goto_filename = base + ".goto"
    c_filename = base + ".c"
    symbols_filename = base + ".symbols"

    if EXIT_CODE_SUCCESS != rmc.compile_single_rust_file(args.input, json_filename, args.verbose, args.debug, args.keep_temps, args.mangler, args.dry_run, args.use_abs, args.abs_type, []):
        return 1

    if EXIT_CODE_SUCCESS != rmc.symbol_table_to_gotoc(json_filename, goto_filename, args.verbose, args.keep_temps, args.dry_run):
        return 1

    args.c_lib.append(str(RMC_C_LIB))

    if args.use_abs and args.abs_type == "c-ffi":
        args.c_lib.append(str(RMC_C_STUB))

    if EXIT_CODE_SUCCESS != rmc.link_c_lib(goto_filename, goto_filename, args.c_lib, args.verbose, args.quiet, args.function, args.dry_run):
        return 1

    if args.gen_c:
        if EXIT_CODE_SUCCESS != rmc.goto_to_c(goto_filename, c_filename, args.verbose, args.dry_run):
            return 1

    if args.gen_symbols:
        if EXIT_CODE_SUCCESS != rmc.goto_to_symbols(goto_filename, symbols_filename, args.verbose, args.dry_run):
            return 1

    if "--function" not in args.cbmc_args:
        args.cbmc_args.extend(["--function", args.function])
    
    if args.visualize:
        # Use a separate set of flags for coverage checking (empty for now)
        cover_args = []
        retcode = rmc.run_visualize(goto_filename, args.cbmc_args, cover_args, \
                                    args.verbose, args.quiet, args.keep_temps, \
                                    args.function, args.srcdir, args.wkdir, args.target_dir, args.dry_run)
    else:
        retcode = rmc.run_cbmc(goto_filename, args.cbmc_args, args.verbose, args.quiet, args.dry_run)

    if retcode == CBMC_VERIFICATION_FAILURE_EXIT_CODE and args.allow_cbmc_verification_failure:
        retcode = EXIT_CODE_SUCCESS

    return retcode

def parse_args():
    # Create parser
    def create_parser():
        parser = argparse.ArgumentParser(description="Verify a single Rust file. For more information, see https://github.com/model-checking/rmc.")

        input_group = parser.add_argument_group("Input", "You can pass in the rust file positionally or with the --input flag.")
        input_group.add_argument("input", help="Rust file to verify", nargs="?")
        input_group.add_argument("--input", help="Rust file to verify", dest="input_flag", metavar="INPUT")

        exclude_flags = [
            # In the future we hope to make this configurable in the command line.
            # For now, however, changing this from "main" breaks rmc.
            # Issue: https://github.com/model-checking/rmc/issues/169
            "--function"
        ]
        rmc_flags.add_flags(parser, {"default-target": "."}, exclude_flags=exclude_flags)
        
        return parser

    # Check for conflicting flags
    def validate(args):
        rmc.ensure(not (args.input and args.input_flag), "Please provide a single file to verify.")
        rmc.ensure(args.input or args.input_flag, "Please provide a file to verify.")

    # Fix up args before returning
    def post_process(args):
        # Combine positional and flag argument for input
        args.input = args.input or args.input_flag

        # --quiet overrides --verbose
        if args.quiet:
            args.verbose = False

        # In the future we hope to make this configurable in the command line.
        # For now, however, changing this from "main" breaks rmc.
        # Issue: https://github.com/model-checking/rmc/issues/169
        args.function = "main"

        # Add some CBMC flags by default unless `--no-default-checks` is being used
        if args.default_checks:
            rmc.add_selected_default_cbmc_flags(args)

    parser = create_parser()
    args = parser.parse_args()
    validate(args)
    post_process(args)

    return args

if __name__ == "__main__":
    sys.exit(main())
