[relabel]
allow-unauthenticated = [
    "A-*", "C-*", "E-*", "I-*", "L-*", "P-*", "S-*", "T-*",
    "good-first-issue"
]

[assign]

# Allows shortcuts like `@rustbot ready`
#
# See https://github.com/rust-lang/triagebot/wiki/Shortcuts
[shortcut]
