# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Modifications Copyright Kani Contributors
# See GitHub history for details.
[package]
name = "rustdoc"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

# From upstream librustdoc:
# https://github.com/rust-lang/rust/tree/master/src/librustdoc
# Upstream crate does not list license but Rust statues:
#   Rust is primarily distributed under the terms of both the MIT
#   license and the Apache License (Version 2.0), with portions
#   covered by various BSD-like licenses.

[lib]
path = "lib.rs"

[dependencies]
pulldown-cmark = { version = "0.10", default-features = false }

[package.metadata.rust-analyzer]
rustc_private = true
