[package]
name = "clippy_utils"
version = "0.1.58"
edition = "2021"
publish = false

[dependencies]
if_chain = "1.0"
rustc-semver = "1.1"

[features]
deny-warnings = []
internal-lints = []
metadata-collector-lint = []

[package.metadata.rust-analyzer]
# This crate uses #[feature(rustc_private)]
rustc_private = true
