# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

# A temporary, non-required workflow to notify us when cargo-audit has things to say.
# TODO: Remove this, and make cargo-audit part of release automation (when we have it) instead.
# And maybe also figure out why dependabot wasn't notifying us. :(

name: Cargo Audit
on: [pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
