# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

# Run the regression job on Apple M1 only on commits to `main`
name: Kani CI M1
on:
  push:
    branches:
      - 'main'

env:
  RUST_BACKTRACE: 1

jobs:
  regression:
    runs-on: macos-13-xlarge
    steps:
      - name: Checkout Kani
        uses: actions/checkout@v4

      - name: Setup Kani Dependencies
        uses: ./.github/actions/setup
        with:
          os: macos-13-xlarge

      - name: Execute Kani regression
        run: ./scripts/kani-regression.sh
