# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Auto label PRs based on the files that were changed
#
# This workflow runs on `pull_request_target` because it needs extra write permission.
#
# Thus, we keep this workflow minimal, and the only actions used here are from the same
# verified publisher.
#
# See <https://github.com/actions/labeler/issues/121> for more details.

name: Auto Label
on: pull_request_target

jobs:
  auto-label:
    permissions:
      contents: read
      pull-requests: write
    outputs:
      all-labels: ${{ steps.labeler.outputs.all-labels }}
      new-labels: ${{ steps.labeler.outputs.new-labels }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kani
      uses: actions/checkout@v3

    - name: Label PR
      id: labeler
      uses: actions/labeler@v4
      with:
        dot: true

  trigger-bench:
    # Use restrictive permissions.
    permissions: {}
    needs: auto-label
    if: contains(needs.auto-label.outputs.all-labels, 'Z-BenchCI')
    uses: ./.github/workflows/bench.yml
