# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

# We use block scalar notation to allow us to add ":" to the workflow name.
name: >-
  Nightly: Slow tests

on:
  schedule:
    - cron: "30 5 * * *" # Run this every day at 05:30 UTC
  workflow_dispatch:     # Allow manual dispatching for a custom branch / tag.

env:
  RUST_BACKTRACE: 1

jobs:
  regression:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Checkout Kani
        uses: actions/checkout@v4

      - name: Setup Kani Dependencies
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os }}

      - name: Build Kani
        run: cargo build-dev

      - name: Run Kani's slow tests
        run: ./scripts/kani-slow-tests.sh
